/* автогенерация: python scripts/build_media.py — не править руками */
window.SS_DATA = {
  "shows": {
    "dragon": {
      "photos": [
        "../assets/web/dragon/dragon-001.jpg",
        "../assets/web/dragon/dragon-002.jpg",
        "../assets/web/dragon/dragon-003.jpg",
        "../assets/web/dragon/dragon-004.jpg",
        "../assets/web/dragon/dragon-005.jpg",
        "../assets/web/dragon/dragon-006.jpg",
        "../assets/web/dragon/dragon-007.jpg",
        "../assets/web/dragon/dragon-008.jpg",
        "../assets/web/dragon/dragon-009.jpg",
        "../assets/web/dragon/dragon-010.jpg",
        "../assets/web/dragon/dragon-011.jpg",
        "../assets/web/dragon/dragon-012.jpg",
        "../assets/web/dragon/dragon-013.jpg",
        "../assets/web/dragon/dragon-014.jpg",
        "../assets/web/dragon/dragon-015.jpg",
        "../assets/web/dragon/dragon-016.jpg",
        "../assets/web/dragon/dragon-017.jpg",
        "../assets/web/dragon/dragon-018.jpg",
        "../assets/web/dragon/dragon-019.jpg",
        "../assets/web/dragon/dragon-020.jpg",
        "../assets/web/dragon/dragon-021.jpg",
        "../assets/web/dragon/dragon-022.jpg"
      ],
      "costumes": [],
      "videos": [
        "95Zx38TO_5Q"
      ]
    },
    "fire": {
      "photos": [
        "../assets/web/fire/fire-001.jpg",
        "../assets/web/fire/fire-002.jpg",
        "../assets/web/fire/fire-003.jpg",
        "../assets/web/fire/fire-004.jpg",
        "../assets/web/fire/fire-005.jpg",
        "../assets/web/fire/fire-006.jpg",
        "../assets/web/fire/fire-007.jpg",
        "../assets/web/fire/fire-008.jpg",
        "../assets/web/fire/fire-009.jpg",
        "../assets/web/fire/fire-010.jpg",
        "../assets/web/fire/fire-011.jpg",
        "../assets/web/fire/fire-012.jpg",
        "../assets/web/fire/fire-013.jpg",
        "../assets/web/fire/fire-014.jpg",
        "../assets/web/fire/fire-015.jpg",
        "../assets/web/fire/fire-016.jpg",
        "../assets/web/fire/fire-017.jpg",
        "../assets/web/fire/fire-018.jpg",
        "../assets/web/fire/fire-019.jpg",
        "../assets/web/fire/fire-020.jpg",
        "../assets/web/fire/fire-021.jpg",
        "../assets/web/fire/fire-022.jpg",
        "../assets/web/fire/fire-023.jpg"
      ],
      "costumes": [],
      "videos": [
        "kUXyXDO6O7I",
        "5kWySEToST0",
        "Q4SIaQwPHLs"
      ]
    },
    "ledfire": {
      "photos": [
        "../assets/web/ledfire/ledfire-001.jpg",
        "../assets/web/ledfire/ledfire-002.jpg",
        "../assets/web/ledfire/ledfire-003.jpg",
        "../assets/web/ledfire/ledfire-004.jpg",
        "../assets/web/ledfire/ledfire-005.jpg",
        "../assets/web/ledfire/ledfire-006.jpg",
        "../assets/web/ledfire/ledfire-007.jpg",
        "../assets/web/ledfire/ledfire-008.jpg",
        "../assets/web/ledfire/ledfire-009.jpg",
        "../assets/web/ledfire/ledfire-010.jpg",
        "../assets/web/ledfire/ledfire-011.jpg",
        "../assets/web/ledfire/ledfire-012.jpg",
        "../assets/web/ledfire/ledfire-013.jpg",
        "../assets/web/ledfire/ledfire-014.jpg"
      ],
      "costumes": [],
      "videos": [
        "aq-PXZIlsyo",
        "NwEsu64rFzY"
      ]
    },
    "led": {
      "photos": [
        "../assets/web/led/led-001.jpg",
        "../assets/web/led/led-002.jpg",
        "../assets/web/led/led-003.jpg",
        "../assets/web/led/led-004.jpg",
        "../assets/web/led/led-005.jpg",
        "../assets/web/led/led-006.jpg",
        "../assets/web/led/led-007.jpg",
        "../assets/web/led/led-008.jpg",
        "../assets/web/led/led-009.jpg",
        "../assets/web/led/led-010.jpg"
      ],
      "costumes": [
        "../assets/web/led-costumes/led-costumes-001.jpg",
        "../assets/web/led-costumes/led-costumes-002.jpg",
        "../assets/web/led-costumes/led-costumes-003.jpg",
        "../assets/web/led-costumes/led-costumes-004.jpg",
        "../assets/web/led-costumes/led-costumes-005.jpg",
        "../assets/web/led-costumes/led-costumes-006.jpg",
        "../assets/web/led-costumes/led-costumes-007.jpg",
        "../assets/web/led-costumes/led-costumes-008.jpg",
        "../assets/web/led-costumes/led-costumes-009.jpg",
        "../assets/web/led-costumes/led-costumes-010.jpg"
      ],
      "videos": [
        "v3MyA-lNGok",
        "U4-_8da2uuI",
        "Ain3sUrpU2w"
      ]
    },
    "stilts": {
      "photos": [
        "../assets/web/stilts/stilts-001.jpg",
        "../assets/web/stilts/stilts-002.jpg",
        "../assets/web/stilts/stilts-003.jpg",
        "../assets/web/stilts/stilts-004.jpg",
        "../assets/web/stilts/stilts-005.jpg",
        "../assets/web/stilts/stilts-006.jpg",
        "../assets/web/stilts/stilts-007.jpg",
        "../assets/web/stilts/stilts-008.jpg",
        "../assets/web/stilts/stilts-009.jpg",
        "../assets/web/stilts/stilts-010.jpg",
        "../assets/web/stilts/stilts-011.jpg",
        "../assets/web/stilts/stilts-012.jpg",
        "../assets/web/stilts/stilts-013.jpg",
        "../assets/web/stilts/stilts-014.jpg",
        "../assets/web/stilts/stilts-015.jpg",
        "../assets/web/stilts/stilts-016.jpg",
        "../assets/web/stilts/stilts-017.jpg",
        "../assets/web/stilts/stilts-018.jpg",
        "../assets/web/stilts/stilts-019.jpg",
        "../assets/web/stilts/stilts-020.jpg",
        "../assets/web/stilts/stilts-021.jpg",
        "../assets/web/stilts/stilts-022.jpg",
        "../assets/web/stilts/stilts-023.jpg",
        "../assets/web/stilts/stilts-024.jpg",
        "../assets/web/stilts/stilts-025.jpg",
        "../assets/web/stilts/stilts-026.jpg",
        "../assets/web/stilts/stilts-027.jpg",
        "../assets/web/stilts/stilts-028.jpg",
        "../assets/web/stilts/stilts-029.jpg",
        "../assets/web/stilts/stilts-030.jpg",
        "../assets/web/stilts/stilts-031.jpg",
        "../assets/web/stilts/stilts-032.jpg",
        "../assets/web/stilts/stilts-033.jpg",
        "../assets/web/stilts/stilts-034.jpg",
        "../assets/web/stilts/stilts-035.jpg",
        "../assets/web/stilts/stilts-036.jpg",
        "../assets/web/stilts/stilts-037.jpg",
        "../assets/web/stilts/stilts-038.jpg",
        "../assets/web/stilts/stilts-039.jpg",
        "../assets/web/stilts/stilts-040.jpg",
        "../assets/web/stilts/stilts-041.jpg",
        "../assets/web/stilts/stilts-042.jpg",
        "../assets/web/stilts/stilts-043.jpg",
        "../assets/web/stilts/stilts-044.jpg",
        "../assets/web/stilts/stilts-045.jpg",
        "../assets/web/stilts/stilts-046.jpg",
        "../assets/web/stilts/stilts-047.jpg",
        "../assets/web/stilts/stilts-048.jpg",
        "../assets/web/stilts/stilts-049.jpg",
        "../assets/web/stilts/stilts-050.jpg",
        "../assets/web/stilts/stilts-051.jpg",
        "../assets/web/stilts/stilts-052.jpg",
        "../assets/web/stilts/stilts-053.jpg",
        "../assets/web/stilts/stilts-054.jpg",
        "../assets/web/stilts/stilts-055.jpg",
        "../assets/web/stilts/stilts-056.jpg",
        "../assets/web/stilts/stilts-057.jpg",
        "../assets/web/stilts/stilts-058.jpg",
        "../assets/web/stilts/stilts-059.jpg"
      ],
      "costumes": [
        "../assets/web/stilt-costumes/stilt-costumes-001.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-002.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-003.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-004.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-005.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-006.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-007.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-008.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-009.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-010.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-011.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-012.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-013.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-014.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-015.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-016.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-017.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-018.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-019.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-020.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-021.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-022.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-023.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-024.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-025.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-026.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-027.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-028.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-029.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-030.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-031.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-032.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-033.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-034.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-035.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-036.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-037.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-038.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-039.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-040.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-041.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-042.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-043.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-044.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-045.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-046.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-047.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-048.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-049.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-050.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-051.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-052.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-053.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-054.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-055.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-056.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-057.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-058.jpg",
        "../assets/web/stilt-costumes/stilt-costumes-059.jpg"
      ],
      "videos": [
        "epn4YnmNrQ8",
        "wogKA0crrt0"
      ]
    }
  },
  "hero": "../assets/web/hero/hero.mp4",
  "heroPoster": "../assets/web/hero/hero-poster.jpg",
  "reel": "a_CLhJkdnGg"
};
